import { documentToReactComponents } from '@contentful/rich-text-react-renderer'
import Banner from '@/components/Banner'
import { BlogPostProps } from '@/interfaces/blogPost'
import { getPostBySlug } from '@/utils/apolloContentfulClient'
import { options } from '@/utils/richTextParse'
import Head from 'next/head'
import styles from '@/styles/PostDetailPage.module.css'

export default function PostDetail(props: BlogPostProps) {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner image={props.image}></Banner>
      <main className="page">
        <div className={styles.pageTitle}>
          <h1>{props.title}</h1>
        </div>
        {props?.body?.json?.content?.map((item: any) =>
          documentToReactComponents(item, options(props.body.links)),
        )}
      </main>
    </>
  )
}

export async function getServerSideProps(context: any) {
  const { resolvedUrl } = context
  const pageSlug = resolvedUrl.split('/')?.[2] || '/'
  const post = await getPostBySlug(`/${pageSlug}`)
  return {
    props: {
      ...post,
    },
  }
}
