import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { getMainNavigationMenu, getPage } from '@/utils/apolloContentfulClient'
import componentMapping from '@/utils/contentfulComponentMapping'
import { ContentfulBase } from '@/interfaces/contentfulBase'
import { documentToReactComponents } from '@contentful/rich-text-react-renderer'
import { options } from '@/utils/richTextParse'
import BlogTiles from '@/components/cms/blogTile/BlogTiles'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props: any) {
  const { page, subCategories, relatedPosts } = props
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>
          {page.title && <h1>{page.title}</h1>}
          {page.text &&
            page?.text?.json?.content?.map((item: any) =>
              documentToReactComponents(item, options(page?.text?.links)),
            )}
          {/* {subCategories && subCategories.length > 0 && (
            <BlogTiles
              title={'Sub Categories'}
              blogItemsCollection={{ items: [...subCategories] }}
            />
          )}
          {relatedPosts && relatedPosts.length > 0 && (
            <BlogTiles
              title={'Posts Related'}
              blogItemsCollection={{ items: [...relatedPosts] }}
            />
          )} */}
          {page.blocksCollection.items.length > 0 &&
            page.blocksCollection.items.map((item: any) => {
              const componentName = item?.['__typename']
              const Component = componentMapping[componentName]
              if (componentName === 'Placeholder') {
                return (
                  <>
                    <BlogTiles
                      title={
                        item.type === 'Posts'
                          ? 'Posts Related'
                          : 'Sub Categories'
                      }
                      blogItemsCollection={{
                        items:
                          item.type === 'Posts'
                            ? [...relatedPosts]
                            : [...subCategories],
                      }}
                    />
                  </>
                )
              }
              return Component ? (
                <Component key={`${item.sys.id} ${Math.random()}`} {...item} />
              ) : (
                <div key={`${item.sys.id} ${Math.random()}`}>
                  In Progress...
                </div>
              )
            })}
        </>
      </main>
    </>
  )
}

export async function getServerSideProps(context: any) {
  const { resolvedUrl } = context
  const page = await getPage(resolvedUrl)
  return {
    props: {
      page: page,
      revalidate: 10,
    },
  }
}

// Use graphql without apollo client
// Please import contentfulClient to use this way
// export async function getServerSideProps() {
//  const blogPosts = await ContentfulApi.getAllContentfulBlogPosts();
//   console.log(blogPosts);
//   return {
//     props: {
//       posts: blogPosts,
//     },
//   };
// }

// export async function getServerSideProps() {
//  const blogPosts = await getAllContentfulBlogPosts()
//   return {
//     props: {
//       posts: blogPosts,
//     },
//   };
// }
