import Head from 'next/head'
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css'
import { getAllContentfulBlogPosts } from '@/utils/apolloContentfulClient';
import componentMapping from '@/utils/contentfulComponentMapping';
import { ContentfulBase } from '@/interfaces/contentfulBase';

const inter = Inter({ subsets: ['latin'] })

export default function Home(props: any) {
  console.log(props);
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {props.posts.map((item: ContentfulBase) => {
            const componentName = item?.['__typename']
            const Component = componentMapping[componentName];
            return <Component key={item.sys.id} {...props} />;
          })}
        </div>
      </main>
    </>
  )
}

// Use graphql without apollo client
// Please import contentfulClient to use this way
// export async function getServerSideProps() {
//  const blogPosts = await ContentfulApi.getAllContentfulBlogPosts();
//   console.log(blogPosts);
//   return {
//     props: {
//       posts: blogPosts,
//     },
//   };
// }

export async function getServerSideProps() {
 const blogPosts = await getAllContentfulBlogPosts()
  return {
    props: {
      posts: blogPosts,
    },
  };
}